# Generated by Django 5.0.3 on 2024-03-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название:')),
                ('content', models.TextField(verbose_name='О секции:')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото:')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания:')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата последнего редактирования:')),
            ],
        ),
    ]
